AWSTemplateFormatVersion: 2010-09-09
Description: Unit 1 - Single CloudFormation Template for S3 with CloudFront

Parameters:
  pAppName:
    type: "string"
    default: "ec-council-unit1"

Resources:
  rS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref pAppName

  rCloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: "Origin Access for CloudFront - S3"
        Name: !Ref pAppName
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  rCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - rS3Bucket
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: "ec-council-unit1.s3.us-east-1.amazonaws.com"
            Id: !Ref pAppName
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt rCloudFrontOriginAccessControl.Id
        Enabled: "true"
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        HttpVersion: http2
        Aliases:
          - example.com
        ViewerCertificate:
          AcmCertificateArn: "arn:aws:acm:us-east-1:Id-of-IAM-user:certificate/1xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx"
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          Compress: true
          TargetOriginId: ec-council-unit1
          ForwardedValues:
            QueryString: "false"
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https

  rBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref pAppName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action: "s3:GetObject"
            Resource: "arn:aws:s3:::ec-council-unit1/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::Id-of-IAM-user:distribution/${CloudFrontDistribution}"

  Outputs:
    S3BucketName:
      Value:
        Ref: rS3Bucket

    OriginAccessControl:
      Value:
        Ref: rCloudFrontOriginAccessControl

    CloudFrontDist:
      Value:
        Ref: rCloudFrontDistribution
